// Code generated by terraform-generator DO NOT EDIT.
package resource_assign_roles_to_user

import (
	"context"
	"github.com/Lenstra/terraform-provider-logto/client"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/path"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ resource.Resource                = &assignRolesToUserResource{}
	_ resource.ResourceWithConfigure   = &assignRolesToUserResource{}
	_ resource.ResourceWithImportState = &assignRolesToUserResource{}
)

type assignRolesToUserResource struct {
	client *client.Client
}

func AssignRolesToUserResource() resource.Resource {
	return &assignRolesToUserResource{}
}

func (r *assignRolesToUserResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_assign_roles_to_user"
}

func (r *assignRolesToUserResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = AssignRolesToUserResourceSchema(ctx)
}

func (r *assignRolesToUserResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		return
	}
	r.client = client
}

func (r *assignRolesToUserResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
