// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_logto

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func LogtoProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type LogtoModel struct {
}
