provider:
  name: logto

resources:
  application:
    read:
      path: /api/applications/{id}
      method: GET
    create:
      path: /api/applications
      method: POST
    update:
      path: /api/applications/{id}
      method: PUT
    delete:
      path: /api/applications/{id}
      method: DELETE
    schema:
      ignores:
        - type
        - oidcClientMetadata
        - createdAt
        - customClientMetadata
        - customData
        - secret
        - protectedAppMetadata
  user:
    read:
      path: /api/users/{userId}
      method: GET
    create:
      path: /api/users
      method: POST
    update:
      path: /api/users/{userId}
      method: PATCH
    delete:
      path: /api/users/{userId}
      method: DELETE
    schema:
      ignores:
        - username
        - primaryEmail
        - primaryPhone
        - avatar
        - customData
        - identities
        - lastSignInAt
        - createdAt
        - updatedAt
        - profile.address
        - profile.birthdate
        - profile.gender
        - profile.locale
        - profile.preferredUsername
        - profile.profile
        - profile.website
        - profile.zoneinfo
        - applicationId
        - isSuspended
        - hasPassword
        - includeSsoIdentities
        - lastSignInAt
        - password
        - passwordAlgorithm
        - passwordDigest
        - ssoIdentities
        - userId
  api_resource:
    read:
      path: /api/resources/{id}
      method: GET
    create:
      path: /api/resources
      method: POST
    update:
      path: /api/resources/{id}
      method: PATCH
    delete:
      path: /api/resources/{id}
      method: DELETE
    schema:
      ignores:
        - tenantId
        - indicator
        - accessTokenTtl
  api_resource_scope:
    read:
      path: /api/resources/{resourceId}/scopes
      method: GET
    create:
      path: /api/resources/{resourceId}/scopes
      method: POST
    update:
      path: /api/resources/{resourceId}/scopes/{scopeId}
      method: PATCH
    delete:
      path: /api/resources/{resourceId}/scopes/{scopeId}
      method: DELETE
    schema:
      ignores:
        - page
        - page_size
        - search_params
        - resourceId
  role:
    read:
      path: /api/roles/{id}
      method: GET
    create:
      path: /api/roles
      method: POST
    update:
      path: /api/roles/{id}
      method: PATCH
    delete:
      path: /api/roles/{id}
      method: DELETE
    schema:
      ignores:
        - tenantId
        - scopeIds
        - type
  # Used to generate the base of the resource schema contained in provider_code_extra.
  # The full resource cannot be generated using generator_config, as it has no attributes (all are ignored in this file).
  # The 'page' attribute is generated automatically in the generated file, but it is not useful.
  # just keep it here to generate the code (and not have an error with generator), then remove it from the generated code.
  # assign_roles_to_user:
  #   read:
  #     path: /api/users/{userId}/roles
  #     method: GET
  #   create:
  #     path: /api/users/{userId}/roles
  #     method: POST
  #   update:
  #     path: /api/users/{userId}/roles
  #     method: PUT
  #   delete:
  #     path: /api/users/{userId}/roles
  #     method: DELETE
  #   schema:
  #     ignores:
  #       - roleIds # We will set this to types.Set instead of types.List so remove it from generation
  #       - userId # Need to be required but generator make it optional/computed
  #       - page_size (IDK why included here)
  #       - search_params (IDK why included here)

datasources: []
