provider:
  name: logto

resources:
  application:
    read:
      path: /api/applications/{id}
      method: GET
    create:
      path: /api/applications
      method: POST
    update:
      path: /api/applications/{id}
      method: PUT
    delete:
      path: /api/applications/{id}
      method: DELETE
    schema:
      ignores:
        - type
        - oidcClientMetadata
        - createdAt
        - customClientMetadata
        - customData
        - secret
        - protectedAppMetadata
  user:
    read:
      path: /api/users/{userId}
      method: GET
    create:
      path: /api/users
      method: POST
    update:
      path: /api/users/{userId}
      method: PATCH
    delete:
      path: /api/users/{userId}
      method: DELETE
    schema:
      ignores:
       - username
       - primaryEmail
       - primaryPhone
       - avatar
       - customData
       - identities
       - lastSignInAt
       - createdAt
       - updatedAt
       - profile.address
       - profile.birthdate
       - profile.gender
       - profile.locale
       - profile.preferredUsername
       - profile.profile
       - profile.website
       - profile.zoneinfo
       - applicationId
       - isSuspended
       - hasPassword
       - includeSsoIdentities
       - lastSignInAt
       - password
       - passwordAlgorithm
       - passwordDigest
       - ssoIdentities
       - userId

data_sources:
 application:
  read:
    path: /api/applications/{id}
    method: GET
  schema:
    ignores:
      - secret
      - oidcClientMetadata
      - createdAt
      - customClientMetadata
      - customData
      - isAdmin
      - isThirdParty
      - protectedAppMetadata
