// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_application

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ApplicationDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type ApplicationModel struct {
	Name types.String `tfsdk:"name"`
}
