package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"
	"unicode"

	tfgen "github.com/Lenstra/terraform-provider-logto/scripts/terraform-generator"
)

func main() {
	err := Main()
	if err != nil {
		log.Fatalf("err: %v", err)
	}
}

func Main() error {
	ctx := context.Background()
	spec, extra, err := tfgen.Load(ctx)
	if err != nil {
		return err
	}

	tfgen.Update(spec, extra)

	content, err := json.MarshalIndent(spec, "", "\t")
	if err != nil {
		return err
	}
	err = os.WriteFile("provider_code_spec.json", content, 0o644)
	if err != nil {
		return err
	}

	input := "provider_code_spec.json"
	output := "internal/provider"
	if err := generate(input, output); err != nil {
		return err
	}
	return generateAdditionalFiles(output)
}

func generate(input, output string) error {
	cmd := exec.Command(
		"tfplugingen-framework",
		"generate",
		"all",
		"--input="+input,
		"--output="+output,
	)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func generateAdditionalFiles(output string) error {
	entries, err := os.ReadDir(output)
	if err != nil {
		return err
	}

	type genInfo struct {
		templateFunc func(string, string) string
		suffix       string
	}

	generators := map[string]genInfo{
		"resource_":   {ressourceTemplate, "_resource_impl_gen.go"},
		"datasource_": {datasourceTemplate, "_datasource_impl_gen.go"},
	}

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		for prefix, info := range generators {
			if strings.HasPrefix(entry.Name(), prefix) {
				packageName := strings.TrimPrefix(entry.Name(), prefix)
				name := toCamelCase(packageName)
				path := fmt.Sprintf("internal/provider/%s/%s%s", entry.Name(), packageName, info.suffix)
				content := []byte(info.templateFunc(packageName, name))
				if err := os.WriteFile(path, content, 0o644); err != nil {
					return err
				}
				break
			}
		}
	}

	return nil
}

func ressourceTemplate(packageName, resourceName string) string {
	noImportState := map[string]struct{}{
		"api_resource_scope": {},
	}

	skipImportState := false
	if _, found := noImportState[packageName]; found {
		skipImportState = true
	}

	importStateBlock := ""

	varBlock := "_ resource.Resource                = &" + resourceName + "Resource{}\n" +
		"\t_ resource.ResourceWithConfigure   = &" + resourceName + "Resource{}"

	imports := `"context"
	"github.com/Lenstra/terraform-provider-logto/client"
	"github.com/hashicorp/terraform-plugin-framework/resource"`

	if !skipImportState {
		importStateBlock = fmt.Sprintf(`func (r *%[1]sResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}`, resourceName)

		varBlock += "\n\t_ resource.ResourceWithImportState = &" + resourceName + "Resource{}"

		imports += `
	"github.com/hashicorp/terraform-plugin-framework/path"`
	}

	return fmt.Sprintf(`// Code generated by terraform-generator DO NOT EDIT.
package resource_%[3]s

import (
	%[4]s
)

// Ensure the implementation satisfies the expected interfaces.
var (
	%[5]s
)

type %[1]sResource struct {
	client *client.Client
}

func %[2]sResource() resource.Resource {
	return &%[1]sResource{}
}

func (r *%[1]sResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_%[3]s"
}

func (r *%[1]sResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = %[2]sResourceSchema(ctx)
}

func (r *%[1]sResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		return
	}
	r.client = client
}

%[6]s
`, resourceName, toPascalCase(packageName), packageName, imports, varBlock, importStateBlock)
}

func datasourceTemplate(packageName, datasourceName string) string {
	return fmt.Sprintf(`// Code generated by terraform-generator DO NOT EDIT.
package datasource_%[3]s

import (
	"context"

	"github.com/Lenstra/terraform-provider-logto/client"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
)

// Ensure the implementation satisfies the expected interfaces.
var _ datasource.DataSource = &%[1]sDataSource{}

type %[1]sDataSource struct {
	client *client.Client
}

func %[2]sDataSource() datasource.DataSource {
	return &%[1]sDataSource{}
}

func (d *%[1]sDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_%[1]s"
}

func (d *%[1]sDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = %[2]sDataSourceSchema(ctx)
}

func (d *%[1]sDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	if client, ok := req.ProviderData.(*client.Client); ok {
		d.client = client
	}
}

`, datasourceName, toPascalCase(packageName), packageName)
}

func toCamelCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || unicode.IsSpace(r)
	})

	for i, p := range parts {
		if len(p) > 0 {
			if i == 0 {
				parts[i] = strings.ToLower(p)
			} else {
				parts[i] = strings.ToUpper(p[:1]) + strings.ToLower(p[1:])
			}
		}
	}
	return strings.Join(parts, "")
}

func toPascalCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || unicode.IsSpace(r)
	})
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + strings.ToLower(p[1:])
		}
	}
	return strings.Join(parts, "")
}
